apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ksm-scale-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ksm-scale-operator-role
subjects:
- kind: ServiceAccount
  name: ksm-scale-operator
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ksm-scale-operator-rolebinding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ksm-scale-operator-role
subjects:
- kind: ServiceAccount
  name: ksm-scale-operator
  namespace: monitoring